import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // PDF.js worker (minified file)
    "public/pdf.worker.min.mjs",
    // Test coverage output (generated by vitest)
    "coverage/**",
    "src/generated/**",
    "node_modules/**",
  ]),
]);

export default eslintConfig;
