"use client";

import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import Image from "next/image";
import { supabase } from "@/lib/supabase";
import { ensureFreshImageUrl } from "@/lib/utils/general";
import { useBlockBodyScroll } from "@/hooks/useBlockBodyScroll";
import {
  MarketConditionsCard,
  type MarketConditionsCardProps,
} from "@/components/shared/MarketConditionsCard";
import { ImagePreviewLightbox } from "@/components/shared/ImagePreviewLightbox";
import {
  mapMarketConditionFromDb,
  mapEntryQualityFromDb,
} from "@/components/trades/hooks/useTradeForm";
import { SharePageSkeleton } from "@/components/skeletons/SharePageSkeleton";
import type { JournalEntry, JournalImage } from "@/types";

// Mapeamento de timeframes para labels em português
const TIMEFRAME_LABELS: Record<string, string> = {
  tfM: "Mensal",
  tfW: "Semanal",
  tfD: "Diário",
  tfH4: "4H",
  tfH1: "1H",
  tfM15: "M15",
  tfM5: "M5",
  tfM3: "M3/M1",
};

export default function SharePage() {
  const params = useParams();
  const token = params?.token as string;

  const [entry, setEntry] = useState<JournalEntry | null>(null);
  const [images, setImages] = useState<JournalImage[]>([]);
  const [tradeContext, setTradeContext] = useState<MarketConditionsCardProps | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lightboxImage, setLightboxImage] = useState<string | null>(null);

  // Block body scroll when lightbox is open
  useBlockBodyScroll(!!lightboxImage);

  // Reset hint when closing lightbox
  const handleCloseLightbox = () => {
    setLightboxImage(null);
  };

  useEffect(() => {
    if (!token) return;

    // Validate if token is a valid UUID
    // The token is a UUID generated by Supabase (or crypto.randomUUID)
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
    if (!uuidRegex.test(token)) {
      // eslint-disable-next-line react-hooks/set-state-in-effect
      setError("Link inválido");
      setLoading(false);
      return;
    }

    const loadSharedEntry = async () => {
      try {
        // Get shared journal by token
        const { data: sharedData, error: sharedError } = await supabase
          .from("shared_journals")
          .select("journal_entry_id, expires_at")
          .eq("share_token", token)
          .single();

        if (sharedError || !sharedData) {
          setError("Link inválido ou expirado");
          setLoading(false);
          return;
        }

        // Check expiration
        if (new Date(sharedData.expires_at) < new Date()) {
          setError("Este link expirou");
          setLoading(false);
          return;
        }

        // Increment view count
        await supabase
          .from("shared_journals")
          .update({
            view_count: supabase.rpc("increment", { row_id: sharedData.journal_entry_id }),
          })
          .eq("share_token", token);

        // Get journal entry
        const { data: entryData, error: entryError } = await supabase
          .from("journal_entries")
          .select("*")
          .eq("id", sharedData.journal_entry_id)
          .single();

        if (entryError || !entryData) {
          setError("Entrada não encontrada");
          setLoading(false);
          return;
        }

        // Get images and map from DB format
        const { data: imagesData } = await supabase
          .from("journal_images")
          .select("*")
          .eq("journal_entry_id", sharedData.journal_entry_id)
          .order("display_order", { ascending: true });

        setEntry({
          id: entryData.id,
          userId: entryData.user_id,
          accountId: entryData.account_id,
          date: entryData.date,
          title: entryData.title,
          asset: entryData.asset,
          tradeIds: entryData.trade_id ? [entryData.trade_id] : [],
          images: [],
          emotion: entryData.emotion,
          analysis: entryData.analysis,
          notes: entryData.notes,
          createdAt: entryData.created_at,
          updatedAt: entryData.updated_at,
        });

        // Map images from DB snake_case to camelCase format
        // Ensure all URLs are complete with Supabase storage base
        const mappedImages: JournalImage[] = (imagesData || []).map(
          (img: {
            id: string;
            user_id: string;
            journal_entry_id: string;
            url: string;
            path: string;
            timeframe: string;
            display_order: number;
            created_at: string;
          }) => ({
            id: img.id,
            userId: img.user_id,
            journalEntryId: img.journal_entry_id,
            url: ensureFreshImageUrl(img.url), // Ensure complete URL
            path: img.path,
            timeframe: img.timeframe,
            displayOrder: img.display_order,
            createdAt: img.created_at,
          })
        );
        setImages(mappedImages);

        // Fetch linked trade via Bridge (RPC)
        // Fetch linked trade via Bridge (RPC)
        const { data: bridgeResponse, error: bridgeError } = await supabase.rpc(
          "get_shared_entry_bridge",
          { token_input: token }
        );

        if (bridgeError) {
          console.error("[SharePage] Bridge RPC error:", bridgeError);
        } else if (bridgeResponse?.error) {
          console.error("[SharePage] Bridge logic error:", bridgeResponse.error);
        } else if (bridgeResponse?.data) {
          const tradeData = bridgeResponse.data;

          const confluencesArray = tradeData.tags
            ? tradeData.tags
                .split(",")
                .map((t: string) => t.trim())
                .filter(Boolean)
            : [];

          const hasData = Boolean(
            tradeData.market_condition_v2 ||
            tradeData.strategy ||
            tradeData.tf_analise ||
            tradeData.tf_entrada ||
            tradeData.setup ||
            tradeData.htf_aligned !== null ||
            confluencesArray.length > 0 ||
            tradeData.entry_quality ||
            tradeData.pd_array
          );

          if (hasData) {
            setTradeContext({
              condition: mapMarketConditionFromDb(tradeData.market_condition_v2) || undefined,
              strategy: tradeData.strategy || undefined,
              strategyIcon: tradeData.strategy_icon || undefined,
              tfAnalise: tradeData.tf_analise || undefined,
              tfEntrada: tradeData.tf_entrada || undefined,
              setup: tradeData.setup || undefined,
              htfAligned: tradeData.htf_aligned ?? undefined,
              confluences: confluencesArray.length > 0 ? confluencesArray : undefined,
              evaluation: mapEntryQualityFromDb(tradeData.entry_quality) || undefined,
              pdArray: tradeData.pd_array || undefined,
            });
          }
        }

        setLoading(false);
      } catch (err) {
        console.error("Error loading shared entry:", err);
        setError("Erro ao carregar entrada compartilhada");
        setLoading(false);
      }
    };

    loadSharedEntry();
  }, [token]);

  // Parse notes JSON
  const parsedNotes = entry?.notes
    ? (() => {
        try {
          return JSON.parse(entry.notes);
        } catch {
          return null;
        }
      })()
    : null;

  if (loading) {
    return <SharePageSkeleton />;
  }

  if (error || !entry) {
    return (
      <div
        className="flex min-h-screen items-center justify-center bg-cover bg-center bg-no-repeat"
        style={{
          backgroundImage:
            "linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.8)), url(/images/share-bg.jpg)",
        }}
      >
        <div className="text-center">
          <div className="mb-4 text-6xl">🔗</div>
          <h1 className="mb-2 text-2xl font-bold text-gray-100">
            {error || "Entrada não encontrada"}
          </h1>
          <p className="text-gray-400">Este link pode ter expirado ou sido removido.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="relative min-h-screen px-4 py-12">
      {/* Fixed Background for better mobile support */}
      <div
        className="pointer-events-none fixed inset-0 z-0 bg-cover bg-center bg-no-repeat"
        style={{
          backgroundImage:
            "linear-gradient(rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0.55)), url(/images/share-bg.jpg)",
        }}
      />

      <div className="relative z-10 mx-auto max-w-4xl">
        {/* Header */}
        <div className="mb-8 text-center">
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-4 py-2">
            <span className="text-emerald-400">🔗</span>
            <span className="text-sm font-medium text-emerald-400">Entrada Compartilhada</span>
          </div>
          <h1 className="mb-2 text-3xl font-bold text-gray-100">{entry.title}</h1>
          <div className="flex items-center justify-center gap-4 text-sm text-gray-400">
            <span>📅 {new Date(entry.date).toLocaleDateString("pt-BR")}</span>
            {entry.asset && <span>📊 {entry.asset}</span>}
          </div>
        </div>

        {/* Market Conditions Section */}
        {tradeContext && (
          <div className="mb-8">
            <MarketConditionsCard {...tradeContext} />
          </div>
        )}

        {/* Analyses (Images) Section */}
        {images.length > 0 && (
          <div className="mb-8">
            <h2 className="mb-4 text-xl font-semibold text-gray-200">📸 Análises</h2>
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              {images.map((img) => (
                <div
                  key={img.id}
                  className="overflow-hidden rounded-lg border border-gray-700 bg-gray-800/50"
                >
                  <div className="border-b border-gray-700 bg-gray-900/50 p-2">
                    <span className="text-xs font-medium text-gray-400">
                      {TIMEFRAME_LABELS[img.timeframe] || img.timeframe}
                    </span>
                  </div>
                  <div
                    className="relative aspect-video w-full cursor-pointer transition-opacity hover:opacity-90"
                    onClick={() => setLightboxImage(img.url)}
                  >
                    <Image
                      src={img.url}
                      alt={TIMEFRAME_LABELS[img.timeframe] || img.timeframe}
                      fill
                      className="object-contain"
                      sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Analysis & Notes */}
        <div className="space-y-6">
          {entry.emotion && (
            <div className="rounded-lg border border-gray-700 bg-gray-800/50 p-6">
              <h3 className="mb-3 text-lg font-semibold text-gray-200">🧠 Estado Emocional</h3>
              <p className="text-gray-300">{entry.emotion}</p>
            </div>
          )}

          {entry.analysis && (
            <div className="rounded-lg border border-gray-700 bg-gray-800/50 p-6">
              <h3 className="mb-3 text-lg font-semibold text-gray-200">📊 Análise</h3>
              <p className="whitespace-pre-wrap text-gray-300">{entry.analysis}</p>
            </div>
          )}

          {parsedNotes && (
            <div className="rounded-lg border border-gray-700 bg-gray-800/50 p-6">
              <h3 className="mb-4 flex items-center gap-2 text-lg font-semibold text-gray-200">
                <span>📜</span> Review
              </h3>
              <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
                <div>
                  <h4 className="mb-2 text-xs font-bold text-green-400 uppercase">Acertos</h4>
                  <p className="text-sm whitespace-pre-wrap text-gray-300">
                    {parsedNotes.technicalWins || "-"}
                  </p>
                </div>
                <div>
                  <h4 className="mb-2 text-xs font-bold text-yellow-400 uppercase">Melhorias</h4>
                  <p className="text-sm whitespace-pre-wrap text-gray-300">
                    {parsedNotes.improvements || "-"}
                  </p>
                </div>
                <div>
                  <h4 className="mb-2 text-xs font-bold text-red-400 uppercase">Erros</h4>
                  <p className="text-sm whitespace-pre-wrap text-gray-300">
                    {parsedNotes.errors || "-"}
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="mt-12 text-center text-sm text-gray-500">
          <p>⏰ Este link expira em breve</p>
        </div>
      </div>

      {/* Lightbox for image preview with Zoom */}
      {lightboxImage && (
        <ImagePreviewLightbox
          images={images.map((img) => ({
            url: img.url,
            label: TIMEFRAME_LABELS[img.timeframe] || img.timeframe,
          }))}
          currentIndex={images.findIndex((img) => img.url === lightboxImage)}
          onClose={handleCloseLightbox}
          onNavigate={(index) => setLightboxImage(images[index].url)}
        />
      )}
    </div>
  );
}
