'use client';

import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import { TransformWrapper, TransformComponent } from 'react-zoom-pan-pinch';
import { supabase } from '@/lib/supabase';
import { ensureFreshImageUrl } from '@/lib/utils/general';
import { useBlockBodyScroll } from '@/hooks/useBlockBodyScroll';
import { MarketConditionsCard, type MarketConditionsCardProps } from '@/components/shared/MarketConditionsCard';
import { mapMarketConditionFromDb, mapEntryQualityFromDb } from '@/components/trades/hooks/useTradeForm';
import { SharePageSkeleton } from '@/components/skeletons/SharePageSkeleton';
import type { JournalEntry, JournalImage } from '@/types';

// Mapeamento de timeframes para labels em português
const TIMEFRAME_LABELS: Record<string, string> = {
    'tfM': 'Mensal',
    'tfW': 'Semanal',
    'tfD': 'Diário',
    'tfH4': '4H',
    'tfH1': '1H',
    'tfM15': 'M15',
    'tfM5': 'M5',
    'tfM3': 'M3/M1',
};

export default function SharePage() {
    const params = useParams();
    const token = params?.token as string;
    
    const [entry, setEntry] = useState<JournalEntry | null>(null);
    const [images, setImages] = useState<JournalImage[]>([]);
    const [tradeContext, setTradeContext] = useState<MarketConditionsCardProps | null>(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [lightboxImage, setLightboxImage] = useState<string | null>(null);
    const [showZoomHint, setShowZoomHint] = useState(true);

    // Block body scroll when lightbox is open
    useBlockBodyScroll(!!lightboxImage);

    // Auto-hide zoom hint after 3 seconds when lightbox is open
    useEffect(() => {
        if (lightboxImage && showZoomHint) {
            const timer = setTimeout(() => setShowZoomHint(false), 3000);
            return () => clearTimeout(timer);
        }
    }, [lightboxImage, showZoomHint]);

    // Reset hint when closing lightbox
    const handleCloseLightbox = () => {
        setLightboxImage(null);
        setShowZoomHint(true);
    };

    useEffect(() => {
        if (!token) return;

        // Validate if token is a valid UUID
        // The token is a UUID generated by Supabase (or crypto.randomUUID)
        const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
        if (!uuidRegex.test(token)) {
            // eslint-disable-next-line react-hooks/set-state-in-effect
            setError('Link inválido');
            setLoading(false);
            return;
        }

        const loadSharedEntry = async () => {
            try {
                // Get shared journal by token
                const { data: sharedData, error: sharedError } = await supabase
                    .from('shared_journals')
                    .select('journal_entry_id, expires_at')
                    .eq('share_token', token)
                    .single();

                if (sharedError || !sharedData) {
                    setError('Link inválido ou expirado');
                    setLoading(false);
                    return;
                }

                // Check expiration
                if (new Date(sharedData.expires_at) < new Date()) {
                    setError('Este link expirou');
                    setLoading(false);
                    return;
                }

                // Increment view count
                await supabase
                    .from('shared_journals')
                    .update({ view_count: supabase.rpc('increment', { row_id: sharedData.journal_entry_id }) })
                    .eq('share_token', token);

                // Get journal entry
                const { data: entryData, error: entryError } = await supabase
                    .from('journal_entries')
                    .select('*')
                    .eq('id', sharedData.journal_entry_id)
                    .single();

                if (entryError || !entryData) {
                    setError('Entrada não encontrada');
                    setLoading(false);
                    return;
                }

                // Get images and map from DB format
                const { data: imagesData } = await supabase
                    .from('journal_images')
                    .select('*')
                    .eq('journal_entry_id', sharedData.journal_entry_id)
                    .order('display_order', { ascending: true });

                setEntry({
                    id: entryData.id,
                    userId: entryData.user_id,
                    accountId: entryData.account_id,
                    date: entryData.date,
                    title: entryData.title,
                    asset: entryData.asset,
                    tradeIds: entryData.trade_id ? [entryData.trade_id] : [],
                    images: [],
                    emotion: entryData.emotion,
                    analysis: entryData.analysis,
                    notes: entryData.notes,
                    createdAt: entryData.created_at,
                    updatedAt: entryData.updated_at,
                });

                // Map images from DB snake_case to camelCase format
                // Ensure all URLs are complete with Supabase storage base
                const mappedImages: JournalImage[] = (imagesData || []).map((img: { id: string; user_id: string; journal_entry_id: string; url: string; path: string; timeframe: string; display_order: number; created_at: string }) => ({
                    id: img.id,
                    userId: img.user_id,
                    journalEntryId: img.journal_entry_id,
                    url: ensureFreshImageUrl(img.url), // Ensure complete URL
                    path: img.path,
                    timeframe: img.timeframe,
                    displayOrder: img.display_order,
                    createdAt: img.created_at,
                }));
                setImages(mappedImages);

                // Fetch linked trade via Bridge (RPC)
                // Fetch linked trade via Bridge (RPC)
                const { data: bridgeResponse, error: bridgeError } = await supabase
                    .rpc('get_shared_entry_bridge', { token_input: token });

                if (bridgeError) {
                    console.error('[SharePage] Bridge RPC error:', bridgeError);
                } else if (bridgeResponse?.error) {
                    console.error('[SharePage] Bridge logic error:', bridgeResponse.error);
                } else if (bridgeResponse?.data) {
                    const tradeData = bridgeResponse.data;
                    
                    const confluencesArray = tradeData.tags
                        ? tradeData.tags.split(',').map((t: string) => t.trim()).filter(Boolean)
                        : [];

                    const hasData = Boolean(
                        tradeData.market_condition_v2 ||
                        tradeData.strategy ||
                        tradeData.tf_analise ||
                        tradeData.tf_entrada ||
                        tradeData.setup ||
                        tradeData.htf_aligned !== null ||
                        confluencesArray.length > 0 ||
                        tradeData.entry_quality ||
                        tradeData.pd_array
                    );

                    if (hasData) {
                        setTradeContext({
                            condition: mapMarketConditionFromDb(tradeData.market_condition_v2) || undefined,
                            strategy: tradeData.strategy || undefined,
                            strategyIcon: tradeData.strategy_icon || undefined,
                            tfAnalise: tradeData.tf_analise || undefined,
                            tfEntrada: tradeData.tf_entrada || undefined,
                            setup: tradeData.setup || undefined,
                            htfAligned: tradeData.htf_aligned ?? undefined,
                            confluences: confluencesArray.length > 0 ? confluencesArray : undefined,
                            evaluation: mapEntryQualityFromDb(tradeData.entry_quality) || undefined,
                            pdArray: tradeData.pd_array || undefined,
                        });
                    }
                }

                setLoading(false);
            } catch (err) {
                console.error('Error loading shared entry:', err);
                setError('Erro ao carregar entrada compartilhada');
                setLoading(false);
            }
        };

        loadSharedEntry();
    }, [token]);

    // Parse notes JSON
    const parsedNotes = entry?.notes ? (() => {
        try {
            return JSON.parse(entry.notes);
        } catch {
            return null;
        }
    })() : null;

    if (loading) {
        return <SharePageSkeleton />;
    }

    if (error || !entry) {
        return (
            <div 
                className="min-h-screen flex items-center justify-center bg-cover bg-center bg-no-repeat"
                style={{ backgroundImage: 'linear-gradient(rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.8)), url(/images/share-bg.jpg)' }}
            >
                <div className="text-center">
                    <div className="text-6xl mb-4">🔗</div>
                    <h1 className="text-2xl font-bold text-gray-100 mb-2">{error || 'Entrada não encontrada'}</h1>
                    <p className="text-gray-400">Este link pode ter expirado ou sido removido.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen py-12 px-4 relative">
            {/* Fixed Background for better mobile support */}
            <div 
                className="fixed inset-0 z-0 bg-cover bg-center bg-no-repeat pointer-events-none"
                style={{ backgroundImage: 'linear-gradient(rgba(0, 0, 0, 0.45), rgba(0, 0, 0, 0.55)), url(/images/share-bg.jpg)' }}
            />

            <div className="max-w-4xl mx-auto relative z-10">
                {/* Header */}
                <div className="text-center mb-8">
                    <div className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-500/10 border border-emerald-500/30 rounded-full mb-4">
                        <span className="text-emerald-400">🔗</span>
                        <span className="text-emerald-400 text-sm font-medium">Entrada Compartilhada</span>
                    </div>
                    <h1 className="text-3xl font-bold text-gray-100 mb-2">{entry.title}</h1>
                    <div className="flex items-center justify-center gap-4 text-sm text-gray-400">
                        <span>📅 {new Date(entry.date).toLocaleDateString('pt-BR')}</span>
                        {entry.asset && <span>📊 {entry.asset}</span>}
                    </div>
                </div>

                {/* Market Conditions Section */}
                {tradeContext && (
                    <div className="mb-8">
                        <MarketConditionsCard {...tradeContext} />
                    </div>
                )}

                {/* Analyses (Images) Section */}
                {images.length > 0 && (
                    <div className="mb-8">
                        <h2 className="text-xl font-semibold text-gray-200 mb-4">📸 Análises</h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {images.map((img) => (
                                <div key={img.id} className="bg-gray-800/50 rounded-lg overflow-hidden border border-gray-700">
                                    <div className="p-2 bg-gray-900/50 border-b border-gray-700">
                                        <span className="text-xs font-medium text-gray-400">
                                            {TIMEFRAME_LABELS[img.timeframe] || img.timeframe}
                                        </span>
                                    </div>
                                    <div
                                        className="relative w-full aspect-video cursor-pointer hover:opacity-90 transition-opacity"
                                        onClick={() => setLightboxImage(img.url)}
                                    >
                                        <Image
                                            src={img.url}
                                            alt={TIMEFRAME_LABELS[img.timeframe] || img.timeframe}
                                            fill
                                            className="object-contain"
                                            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                                        />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* Analysis & Notes */}
                <div className="space-y-6">
                    {entry.emotion && (
                        <div className="bg-gray-800/50 rounded-lg p-6 border border-gray-700">
                            <h3 className="text-lg font-semibold text-gray-200 mb-3">🧠 Estado Emocional</h3>
                            <p className="text-gray-300">{entry.emotion}</p>
                        </div>
                    )}

                    {entry.analysis && (
                        <div className="bg-gray-800/50 rounded-lg p-6 border border-gray-700">
                            <h3 className="text-lg font-semibold text-gray-200 mb-3">📊 Análise</h3>
                            <p className="text-gray-300 whitespace-pre-wrap">{entry.analysis}</p>
                        </div>
                    )}

                    {parsedNotes && (
                        <div className="bg-gray-800/50 rounded-lg p-6 border border-gray-700">
                            <h3 className="text-lg font-semibold text-gray-200 mb-4 flex items-center gap-2">
                                <span>📜</span> Review
                            </h3>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                <div>
                                    <h4 className="text-xs font-bold text-green-400 mb-2 uppercase">Acertos</h4>
                                    <p className="text-sm text-gray-300 whitespace-pre-wrap">
                                        {parsedNotes.technicalWins || '-'}
                                    </p>
                                </div>
                                <div>
                                    <h4 className="text-xs font-bold text-yellow-400 mb-2 uppercase">Melhorias</h4>
                                    <p className="text-sm text-gray-300 whitespace-pre-wrap">
                                        {parsedNotes.improvements || '-'}
                                    </p>
                                </div>
                                <div>
                                    <h4 className="text-xs font-bold text-red-400 mb-2 uppercase">Erros</h4>
                                    <p className="text-sm text-gray-300 whitespace-pre-wrap">
                                        {parsedNotes.errors || '-'}
                                    </p>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="mt-12 text-center text-gray-500 text-sm">
                    <p>⏰ Este link expira em breve</p>
                </div>
            </div>

            {/* Lightbox for image preview with Zoom */}
            {lightboxImage && (
                <div 
                    className="fixed inset-0 z-100 bg-black/90 backdrop-blur-md flex items-center justify-center"
                    onClick={handleCloseLightbox}
                >
                    {/* Close Button */}
                    <button 
                        className="absolute top-4 right-4 text-gray-400 hover:text-white p-2 z-50 bg-black/50 rounded-full transition-colors"
                        onClick={handleCloseLightbox}
                        aria-label="Fechar visualização"
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                            <line x1="18" y1="6" x2="6" y2="18" />
                            <line x1="6" y1="6" x2="18" y2="18" />
                        </svg>
                    </button>

                    {/* Image Label */}
                    <div className="absolute top-4 left-1/2 -translate-x-1/2 bg-black/70 px-4 py-2 rounded-full text-sm font-medium text-cyan-400 z-50 flex gap-2">
                        <span>{TIMEFRAME_LABELS[images.find(img => img.url === lightboxImage)?.timeframe || ''] || images.find(img => img.url === lightboxImage)?.timeframe}</span>
                        {images.length > 1 && (
                            <span className="text-gray-400">
                                ({images.findIndex(img => img.url === lightboxImage) + 1}/{images.length})
                            </span>
                        )}
                    </div>

                    {/* Navigation Arrows */}
                    {images.length > 1 && (
                        <>
                            <button 
                                className="absolute left-4 top-1/2 -translate-y-1/2 p-3 bg-black/60 hover:bg-black/80 text-white rounded-full transition-colors z-50"
                                onClick={(e) => {
                                    e.stopPropagation();
                                    const currentIndex = images.findIndex(img => img.url === lightboxImage);
                                    const prevIndex = currentIndex > 0 ? currentIndex - 1 : images.length - 1;
                                    setLightboxImage(images[prevIndex].url);
                                }}
                                aria-label="Imagem anterior"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                    <polyline points="15 18 9 12 15 6" />
                                </svg>
                            </button>
                            <button 
                                className="absolute right-4 top-1/2 -translate-y-1/2 p-3 bg-black/60 hover:bg-black/80 text-white rounded-full transition-colors z-50"
                                onClick={(e) => {
                                    e.stopPropagation();
                                    const currentIndex = images.findIndex(img => img.url === lightboxImage);
                                    const nextIndex = currentIndex < images.length - 1 ? currentIndex + 1 : 0;
                                    setLightboxImage(images[nextIndex].url);
                                }}
                                aria-label="Próxima imagem"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                    <polyline points="9 18 15 12 9 6" />
                                </svg>
                            </button>
                        </>
                    )}

                    {/* Zoomable Image Container */}
                    <div 
                        className="absolute inset-0 flex items-center justify-center"
                        onClick={e => e.stopPropagation()}
                    >
                        <TransformWrapper
                            initialScale={1}
                            minScale={0.5}
                            maxScale={4}
                            doubleClick={{ mode: 'reset' }}
                            wheel={{ step: 0.1 }}
                            panning={{ 
                                disabled: false,
                                velocityDisabled: true,
                            }}
                            limitToBounds={false}
                            centerOnInit={true}
                            centerZoomedOut={true}
                            onTransformed={(_, state) => {
                                // Update zoom indicator in the DOM
                                const indicator = document.getElementById('share-zoom-indicator');
                                if (indicator) {
                                    indicator.textContent = `${Math.round(state.scale * 100)}%`;
                                    // Update color based on scale
                                    indicator.className = `text-sm min-w-14 text-center font-mono ${
                                        state.scale < 0.99 ? 'text-yellow-300' : state.scale > 1.01 ? 'text-green-300' : 'text-white'
                                    }`;
                                }
                            }}
                        >
                            {({ zoomIn, zoomOut, resetTransform, instance }) => {
                                const scale = instance.transformState.scale;
                                return (
                                    <>
                                        <TransformComponent
                                            wrapperStyle={{
                                                width: '100%',
                                                height: '100%',
                                            }}
                                        >
                                            {/* eslint-disable-next-line @next/next/no-img-element */}
                                            <img
                                                src={lightboxImage}
                                                alt="Preview"
                                                style={{ 
                                                    maxWidth: '100vw',
                                                    maxHeight: '85vh',
                                                    objectFit: 'contain',
                                                    borderRadius: '0.5rem',
                                                    userSelect: 'none',
                                                    WebkitUserDrag: 'none',
                                                    touchAction: 'none',
                                                    cursor: 'grab',
                                                } as React.CSSProperties}
                                                draggable={false}
                                            />
                                        </TransformComponent>
                                        
                                        {/* Zoom Controls */}
                                        <div className="absolute bottom-6 left-1/2 -translate-x-1/2 flex items-center gap-2 bg-black/70 rounded-full px-4 py-2 backdrop-blur-sm z-50">
                                            {/* Reset Button */}
                                            <button 
                                                onClick={() => resetTransform()} 
                                                className="text-white w-8 h-8 flex items-center justify-center hover:bg-white/10 rounded-full transition-colors"
                                                aria-label="Resetar para 100%"
                                                title="Resetar zoom (100%)"
                                            >
                                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                                    <circle cx="11" cy="11" r="8" />
                                                    <line x1="21" y1="21" x2="16.65" y2="16.65" />
                                                </svg>
                                            </button>
                                            
                                            <div className="w-px h-5 bg-white/20" />
                                            
                                            {/* Zoom Out */}
                                            <button 
                                                onClick={() => zoomOut(0.25)} 
                                                className="text-white w-8 h-8 flex items-center justify-center rounded-full transition-colors hover:bg-white/10"
                                                aria-label="Diminuir zoom"
                                            >
                                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                                    <line x1="5" y1="12" x2="19" y2="12" />
                                                </svg>
                                            </button>
                                            
                                            {/* Percentage Indicator */}
                                            <span 
                                                id="share-zoom-indicator"
                                                className="text-sm min-w-14 text-center font-mono text-white"
                                            >
                                                {Math.round(scale * 100)}%
                                            </span>
                                            
                                            {/* Zoom In */}
                                            <button 
                                                onClick={() => zoomIn(0.25)} 
                                                className="text-white w-8 h-8 flex items-center justify-center rounded-full transition-colors hover:bg-white/10"
                                                aria-label="Aumentar zoom"
                                            >
                                                <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                                                    <line x1="12" y1="5" x2="12" y2="19" />
                                                    <line x1="5" y1="12" x2="19" y2="12" />
                                                </svg>
                                            </button>
                                        </div>
                                        
                                        {/* Mobile Zoom Hint */}
                                        {showZoomHint && (
                                            <div className="absolute top-20 left-1/2 -translate-x-1/2 text-xs text-white/80 bg-black/60 px-4 py-2 rounded-full md:hidden z-50 flex items-center gap-2 animate-pulse">
                                                <span>👆</span>
                                                Clique para zoom • Duplo clique para reset
                                            </div>
                                        )}
                                    </>
                                );
                            }}
                        </TransformWrapper>
                    </div>
                </div>
            )}
        </div>
    );
}
