'use client';

import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import Image from 'next/image';
import { supabase } from '@/lib/supabase';
import { ensureFreshImageUrl } from '@/lib/utils';
import type { JournalEntry, JournalImage } from '@/types';

// Mapeamento de timeframes para labels em português
const TIMEFRAME_LABELS: Record<string, string> = {
    'tfM': 'Mensal',
    'tfW': 'Semanal',
    'tfD': 'Diário',
    'tfH4': '4H',
    'tfH1': '1H',
    'tfM15': 'M15',
    'tfM5': 'M5',
    'tfM3': 'M3/M1',
};

export default function SharePage() {
    const params = useParams();
    const token = params?.token as string;
    
    const [entry, setEntry] = useState<JournalEntry | null>(null);
    const [images, setImages] = useState<JournalImage[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);
    const [lightboxImage, setLightboxImage] = useState<string | null>(null);

    useEffect(() => {
        if (!token) return;

        // Validate if token is a valid UUID
        // The token is a UUID generated by Supabase (or crypto.randomUUID)
        const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
        if (!uuidRegex.test(token)) {
            // eslint-disable-next-line react-hooks/set-state-in-effect
            setError('Link inválido');
            setLoading(false);
            return;
        }

        const loadSharedEntry = async () => {
            try {
                // Get shared journal by token
                const { data: sharedData, error: sharedError } = await supabase
                    .from('shared_journals')
                    .select('journal_entry_id, expires_at')
                    .eq('share_token', token)
                    .single();

                if (sharedError || !sharedData) {
                    setError('Link inválido ou expirado');
                    setLoading(false);
                    return;
                }

                // Check expiration
                if (new Date(sharedData.expires_at) < new Date()) {
                    setError('Este link expirou');
                    setLoading(false);
                    return;
                }

                // Increment view count
                await supabase
                    .from('shared_journals')
                    .update({ view_count: supabase.rpc('increment', { row_id: sharedData.journal_entry_id }) })
                    .eq('share_token', token);

                // Get journal entry
                const { data: entryData, error: entryError } = await supabase
                    .from('journal_entries')
                    .select('*')
                    .eq('id', sharedData.journal_entry_id)
                    .single();

                if (entryError || !entryData) {
                    setError('Entrada não encontrada');
                    setLoading(false);
                    return;
                }

                // Get images and map from DB format
                const { data: imagesData } = await supabase
                    .from('journal_images')
                    .select('*')
                    .eq('journal_entry_id', sharedData.journal_entry_id)
                    .order('display_order', { ascending: true });

                setEntry({
                    id: entryData.id,
                    userId: entryData.user_id,
                    accountId: entryData.account_id,
                    date: entryData.date,
                    title: entryData.title,
                    asset: entryData.asset,
                    tradeIds: entryData.trade_id ? [entryData.trade_id] : [],
                    images: [],
                    emotion: entryData.emotion,
                    analysis: entryData.analysis,
                    notes: entryData.notes,
                    createdAt: entryData.created_at,
                    updatedAt: entryData.updated_at,
                });

                // Map images from DB snake_case to camelCase format
                // Ensure all URLs are complete with Supabase storage base
                const mappedImages: JournalImage[] = (imagesData || []).map((img: { id: string; user_id: string; journal_entry_id: string; url: string; path: string; timeframe: string; display_order: number; created_at: string }) => ({
                    id: img.id,
                    userId: img.user_id,
                    journalEntryId: img.journal_entry_id,
                    url: ensureFreshImageUrl(img.url), // Ensure complete URL
                    path: img.path,
                    timeframe: img.timeframe,
                    displayOrder: img.display_order,
                    createdAt: img.created_at,
                }));
                setImages(mappedImages);
                setLoading(false);
            } catch (err) {
                console.error('Error loading shared entry:', err);
                setError('Erro ao carregar entrada compartilhada');
                setLoading(false);
            }
        };

        loadSharedEntry();
    }, [token]);

    // Parse notes JSON
    const parsedNotes = entry?.notes ? (() => {
        try {
            return JSON.parse(entry.notes);
        } catch {
            return null;
        }
    })() : null;

    if (loading) {
        return (
            <div className="min-h-screen bg-linear-to-br from-gray-900 via-gray-800 to-gray-900 flex items-center justify-center">
                <div className="text-emerald-400 text-xl">Carregando...</div>
            </div>
        );
    }

    if (error || !entry) {
        return (
            <div className="min-h-screen bg-linear-to-br from-gray-900 via-gray-800 to-gray-900 flex items-center justify-center">
                <div className="text-center">
                    <div className="text-6xl mb-4">🔗</div>
                    <h1 className="text-2xl font-bold text-gray-100 mb-2">{error || 'Entrada não encontrada'}</h1>
                    <p className="text-gray-400">Este link pode ter expirado ou sido removido.</p>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-linear-to-br from-gray-900 via-gray-800 to-gray-900 py-12 px-4">
            <div className="max-w-4xl mx-auto">
                {/* Header */}
                <div className="text-center mb-8">
                    <div className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-500/10 border border-emerald-500/30 rounded-full mb-4">
                        <span className="text-emerald-400">🔗</span>
                        <span className="text-emerald-400 text-sm font-medium">Entrada Compartilhada</span>
                    </div>
                    <h1 className="text-3xl font-bold text-gray-100 mb-2">{entry.title}</h1>
                    <div className="flex items-center justify-center gap-4 text-sm text-gray-400">
                        <span>📅 {new Date(entry.date).toLocaleDateString('pt-BR')}</span>
                        {entry.asset && <span>📊 {entry.asset}</span>}
                    </div>
                </div>

                {/* Images Grid */}
                {images.length > 0 && (
                    <div className="mb-8">
                        <h2 className="text-xl font-semibold text-gray-200 mb-4">📸 Análises</h2>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            {images.map((img) => (
                                <div key={img.id} className="bg-gray-800/50 rounded-lg overflow-hidden border border-gray-700">
                                    <div className="p-2 bg-gray-900/50 border-b border-gray-700">
                                        <span className="text-xs font-medium text-gray-400">
                                            {TIMEFRAME_LABELS[img.timeframe] || img.timeframe}
                                        </span>
                                    </div>
                                    <div
                                        className="relative w-full aspect-video cursor-pointer hover:opacity-90 transition-opacity"
                                        onClick={() => setLightboxImage(img.url)}
                                    >
                                        <Image
                                            src={img.url}
                                            alt={TIMEFRAME_LABELS[img.timeframe] || img.timeframe}
                                            fill
                                            className="object-contain"
                                            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                                        />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* Analysis & Notes */}
                <div className="space-y-6">
                    {entry.emotion && (
                        <div className="bg-gray-800/50 rounded-lg p-6 border border-gray-700">
                            <h3 className="text-lg font-semibold text-gray-200 mb-3">🧠 Estado Emocional</h3>
                            <p className="text-gray-300">{entry.emotion}</p>
                        </div>
                    )}

                    {entry.analysis && (
                        <div className="bg-gray-800/50 rounded-lg p-6 border border-gray-700">
                            <h3 className="text-lg font-semibold text-gray-200 mb-3">📊 Análise</h3>
                            <p className="text-gray-300 whitespace-pre-wrap">{entry.analysis}</p>
                        </div>
                    )}

                    {parsedNotes && (
                        <div className="bg-gray-800/50 rounded-lg p-6 border border-gray-700">
                            <h3 className="text-lg font-semibold text-gray-200 mb-4 flex items-center gap-2">
                                <span>📜</span> Review
                            </h3>
                            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                                <div>
                                    <h4 className="text-xs font-bold text-green-400 mb-2 uppercase">Acertos</h4>
                                    <p className="text-sm text-gray-300 whitespace-pre-wrap">
                                        {parsedNotes.technicalWins || '-'}
                                    </p>
                                </div>
                                <div>
                                    <h4 className="text-xs font-bold text-yellow-400 mb-2 uppercase">Melhorias</h4>
                                    <p className="text-sm text-gray-300 whitespace-pre-wrap">
                                        {parsedNotes.improvements || '-'}
                                    </p>
                                </div>
                                <div>
                                    <h4 className="text-xs font-bold text-red-400 mb-2 uppercase">Erros</h4>
                                    <p className="text-sm text-gray-300 whitespace-pre-wrap">
                                        {parsedNotes.errors || '-'}
                                    </p>
                                </div>
                            </div>
                        </div>
                    )}
                </div>

                {/* Footer */}
                <div className="mt-12 text-center text-gray-500 text-sm">
                    <p>⏰ Este link expira em breve</p>
                </div>
            </div>

            {/* Lightbox for image preview */}
            {lightboxImage && (
                <div 
                    className="fixed inset-0 z-60 bg-linear-to-br from-black/40 to-black/10 backdrop-blur-md flex items-center justify-center p-4"
                    onClick={() => setLightboxImage(null)}
                >
                    <button 
                        className="absolute top-4 right-4 text-gray-400 hover:text-white p-2"
                        onClick={() => setLightboxImage(null)}
                    >
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
                    </button>

                    <div className="relative max-w-7xl max-h-[90vh] w-full h-full flex items-center justify-center">
                        {images.length > 1 && (
                            <>
                                <button 
                                    className="absolute left-4 top-1/2 -translate-y-1/2 p-2 bg-black/50 hover:bg-black/70 text-white rounded-full transition-colors z-50"
                                    onClick={(e) => {
                                        e.stopPropagation();
                                        const currentIndex = images.findIndex(img => img.url === lightboxImage);
                                        const prevIndex = currentIndex > 0 ? currentIndex - 1 : images.length - 1;
                                        setLightboxImage(images[prevIndex].url);
                                    }}
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="15 18 9 12 15 6"></polyline></svg>
                                </button>
                                <button 
                                    className="absolute right-4 top-1/2 -translate-y-1/2 p-2 bg-black/50 hover:bg-black/70 text-white rounded-full transition-colors z-50"
                                    onClick={(e) => {
                                        e.stopPropagation();
                                        const currentIndex = images.findIndex(img => img.url === lightboxImage);
                                        const nextIndex = currentIndex < images.length - 1 ? currentIndex + 1 : 0;
                                        setLightboxImage(images[nextIndex].url);
                                    }}
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="9 18 15 12 9 6"></polyline></svg>
                                </button>
                            </>
                        )}
                        
                        <div className="relative w-full max-w-5xl h-[85vh]" onClick={e => e.stopPropagation()}>
                            <div className="absolute top-4 left-1/2 -translate-x-1/2 bg-black/60 px-3 py-1 rounded-full text-sm font-medium text-cyan-400 z-10 flex gap-2">
                                <span>{TIMEFRAME_LABELS[images.find(img => img.url === lightboxImage)?.timeframe || ''] || images.find(img => img.url === lightboxImage)?.timeframe}</span>
                                {images.length > 1 && (
                                    <span className="text-gray-400">
                                        ({images.findIndex(img => img.url === lightboxImage) + 1}/{images.length})
                                    </span>
                                )}
                            </div>
                            {/* Using native img tag to avoid Next.js Image optimization issues */}
                            {/* eslint-disable-next-line @next/next/no-img-element */}
                            <img
                                src={lightboxImage}
                                alt="Preview"
                                className="w-full h-full object-contain rounded-lg shadow-2xl"
                            />
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
}
